name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Set up Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 'Install dependencies'
        run: npm install

      - name: 'Lint with ESLint'
        run: npx eslint index.js

      - name: 'Run tests with Mocha'
        run: npx mocha

      - name : 'publish npm'
        uses: js-actions/npm@master
        with:
          args: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


